swagger: '2.0'
info:
  version: '1.0'
  title: "SE2-Proj"
  description: Blank https://github.com/Extrance/CartaBianca-SE2.git
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE