swagger: '2.0'
info:
  version: '1.0'
  title: "Exam-ify"
  description:  https://github.com/Extrance/CartaBianca-SE2.git<br>
                API description for SE2 project<br>
                
                <h2>/</h2><br>
                On main page user can find links to list of users, exams, tasks and groups<br>
                Methods:<ul>
                <li><b>get</b> - display links to /users, /exams, /groups, /tasks (everyone)
                </ul>
                
                <h2>/users</h2><br>
                  On this page user can find a list of all users and view their profiles<br><br>
                  Methods:<ul>
                  <li><b>get</b> - get the list of all users<ul>
                    <li>display the list of ID of all users of the website (everyone)
                    <li>display the list of ID, name and surname of all users of the website (logged in)
                    </ul>
                  <li><b>post</b> - add a user to the system (logged in)
                  </ul>
                
                
                <h2>/users/{id}</h2><br>
                  Page of a specific user with matricola={id}<br>
                  If a user not found, return 404 code<br>
                  Methods:<ul>
                  <li><b>get</b> - get the data of a specific user<ul>
                    <li>display the ID of user (everyone)
                    <li>display ID, name, surname groups he’s a part of (logged in)
                    <li>display ID, name, surname, groups he’s a part of, exams to do, exams done with votes and comments (the page belongs to the logged in user)
                    </ul>
                  <li><b>delete</b> - delete user (page belongs to the logged in user)
                  </ul>
                
                <h2>/exams</h2><br>
                  Page of the exams subpage
                  Methods:<ul>
                  <li><b>get</b> - display the list of names of all exams of the website (everyone)
                  <li><b>post</b> - create a new exam (logged in)
                  </ul>
                
                <h2>/exams/{name}</h2><br>
                Page of a specific exam with name={name}, eventually be able to open the single tasks<br>
                If an exam not found, return 404 code<br>
                Methods:<ul>
                <li><b>get</b> - display the list of exercises (user that have to attend the exam)
                <li><b>post</b> - assign the exam to a group (logged in)
                <li><b>post</b> - decide who is gonna help with reviewing (who is using the exam)
                <li><b>delete</b> - delete the exam (owner of the exam)
                </ul><br>
                
                <h2>/groups</h2><br>
                Page of the groups subpage
                Methods:<ul>
                <li><b>get</b> - display the list of all groups
                <li><b>post</b> - create a new group (logged in)
                </ul>
                
                <h2>/groups/{id}</h2><br>
                Page of a specific group with id={id}
                If a group not found, return 404 code<br>
                Methods:<ul>
                <li><b>get</b> - display data of the group<ul>
                  <li>display the list of users of the group (logged in)
                  <li>display the list of users of the group, exams assigned (part of the group)
                  </ul>
                <li><b>post</b> - manage the members of the group<ul>
                  <li>add a user to the group (admin of the group)
                  <li>remove a user from the group (admin of the group)
                  </ul>
                <li><b>delete</b> - delete the group (admin of the group)
                </ul>
                
                <h2>/tasks</h2><br>
                Page of the tasks subpage
                Methods:<ul>
                <li><b>get</b> - display the list of all tasks (logged in)
                <li><b>post</b> - create a new task (logged in)
                </ul>
                
                
                <h2>/task/{id}</h2><br>
                Page of a specific task with id={id}
                If a task is not found, return 404 code<br>
                Methods:<ul>
                <li><b>get</b> - display the task depending who is viewing<ul>
                  <li>display the task (logged in)
                  <li>display options to answer (user that is taking an exam)
                  </ul>
                <li><b>post</b> - answer the task (user that is taking an exam)
                </ul>
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
    
host: cartabiancase2-automatic.herokuapp.com